export const SPOTS = [

  // ── GARDEN ROUTE ──────────────────────────────────────────────────────────
  {
    id: 'knysna-heads',
    name: 'Knysna Heads',
    region: 'Garden Route',
    aliases: ['knysna heads', 'the heads', 'belvidere', 'white bridge', 'red bridge'],
    lat: -34.0797, lon: 23.0530,
    hasMarine: true, isTidal: true, tidalType: 'permanent',
    exposure: 'open ocean',
    profile: 'Open ocean entry through a narrow tidal channel. Significant S and SW swell penetrates. Strong tidal currents — direction and timing critical. Not suitable above 1.5m swell.',
  },
  {
    id: 'knysna-lagoon',
    name: 'Knysna Lagoon',
    region: 'Garden Route',
    aliases: ['knysna lagoon', 'knysna estuary', 'thesen island', 'yacht club', 'knysna yacht club'],
    lat: -34.0556, lon: 23.0497,
    hasMarine: false, isTidal: true, tidalType: 'permanent',
    exposure: 'sheltered',
    profile: 'Sheltered tidal estuary — permanently connected to the sea. The lagoon is 17km long with entry points from the Heads to Belvidere, White Bridge, Red Bridge and the Yacht Club. No ocean swell penetrates. Conditions driven by local wind. In SE winds above 35-40 km/h the long SE fetch creates significant short steep chop. Tidal currents run throughout — strongest mid-tide, slack near the turns. Spring tides produce stronger flow.',
  },
  {
    id: 'buffalo-bay',
    name: 'Buffalo Bay',
    region: 'Garden Route',
    aliases: ['buffalo bay', 'buffels bay', 'buffelsbay'],
    lat: -34.1082, lon: 22.9897,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Semi-sheltered bay facing SSW. Some S-SW swell penetration but generally calmer than the Heads. Shore break on the sand beach.',
  },
  {
    id: 'wilderness-beach',
    name: 'Wilderness Beach',
    region: 'Garden Route',
    aliases: ['wilderness', 'wilderness beach'],
    lat: -33.9897, lon: 22.5933,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open-ocean beach fully exposed to S and SW swell. Shore break can be heavy. Rip currents possible.',
  },
  {
    id: 'sedgefield-lagoon',
    name: 'Sedgefield Lagoon',
    region: 'Garden Route',
    aliases: ['sedgefield', 'sedgefield lagoon', 'swartvlei'],
    lat: -34.0167, lon: 22.7833,
    hasMarine: false, isTidal: true, tidalType: 'intermittent',
    exposure: 'sheltered',
    profile: 'Sheltered coastal lagoon (Swartvlei). No ocean swell. Wind-driven surface conditions. The mouth to the sea opens and closes seasonally — when closed there is no tidal current and conditions are lake-like. When open, tidal exchange creates current.',
  },
  {
    id: 'wilderness-lagoon',
    name: 'Wilderness Lagoon',
    region: 'Garden Route',
    aliases: ['wilderness lagoon', 'touw river', 'wilderness river'],
    lat: -33.9950, lon: 22.5900,
    hasMarine: false, isTidal: true, tidalType: 'intermittent',
    exposure: 'sheltered',
    profile: 'Sheltered river lagoon (Touw River mouth). Calm flat water when the mouth is closed. When open to the sea, tidal current runs. The mouth opens and closes seasonally — check local conditions before assuming tidal flow.',
  },
  {
    id: 'goukamma-river',
    name: 'Goukamma River',
    region: 'Garden Route',
    aliases: ['goukamma', 'goukamma river', 'gouw kamma', 'goukamma mouth'],
    lat: -34.0833, lon: 22.9333,
    hasMarine: false, isTidal: true, tidalType: 'intermittent',
    exposure: 'sheltered',
    profile: 'River mouth near Buffalo Bay. Sheltered calm water when closed. When the mouth opens to the sea, tidal current flows. The mouth opens and closes depending on rainfall and sea conditions — no tidal current when closed.',
  },
  {
    id: 'mossel-bay',
    name: 'Mossel Bay',
    region: 'Garden Route',
    aliases: ['mossel bay', 'mosselbay'],
    lat: -34.1833, lon: 22.1500,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Protected bay offering shelter from prevailing SW swell. Exposed to SE and E swell. Santos Beach is the main swim spot.',
  },
  {
    id: 'santos-beach',
    name: 'Santos Beach',
    region: 'Garden Route',
    aliases: ['santos', 'santos beach'],
    lat: -34.1757, lon: 22.1396,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Sheltered beach within Mossel Bay, protected from SW swell. One of the calmer Garden Route ocean swims.',
  },
  {
    id: 'victoria-bay',
    name: 'Victoria Bay',
    region: 'Garden Route',
    aliases: ['victoria bay', 'vic bay'],
    lat: -33.9833, lon: 22.5333,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Small exposed cove between George and Wilderness. Full S and SW swell exposure. Shallow reef break. Primarily a surf spot — open water swimmers should assess conditions carefully before entering.',
  },
  {
    id: 'natures-valley',
    name: "Natures Valley",
    region: 'Garden Route',
    aliases: ['natures valley', 'nature valley', 'groot river'],
    lat: -33.9833, lon: 23.5500,
    hasMarine: false, isTidal: true, tidalType: 'intermittent',
    exposure: 'sheltered',
    profile: 'The Groot River lagoon within the Tsitsikamma is where open water swimming happens here — sheltered, calm, and pristine. The mouth opens and closes seasonally; when open, tidal current runs. The ocean beach is exposed and not an OW swim venue. Remote and uncrowded.',
  },
  {
    id: 'keurbooms-river',
    name: 'Keurbooms River',
    region: 'Garden Route',
    aliases: ['keurbooms', 'keurbooms river', 'bitou', 'bitou river', 'keurbooms estuary', 'plett river', 'potjies', 'plettenberg bay', 'plett'],
    lat: -34.0050, lon: 23.4200,
    hasMarine: false, isTidal: true, tidalType: 'permanent',
    exposure: 'sheltered',
    profile: 'Sheltered tidal estuary permanently connected to the sea — the Keurbooms and Bitou rivers meet before the mouth. This is where open water swimmers in the Plett area swim. No swell penetrates. Conditions driven by local wind and tidal state. The swim near Potjies offers calm flat water on most days. Tidal current runs throughout — strongest mid-tide, slack near the turns. Spring tides produce stronger flow.',
  },

  // ── EASTERN CAPE ──────────────────────────────────────────────────────────
  {
    id: 'gqeberha',
    name: 'Gqeberha (Port Elizabeth)',
    region: 'Eastern Cape',
    aliases: ['gqeberha', 'port elizabeth', 'pe beach', 'humewood', 'hobie beach', 'hobie', 'kings beach'],
    lat: -33.9757, lon: 25.6486,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Kings Beach is the primary open water swim venue — long, clean sand, Algoa Bay facing NE. The bay\'s orientation gives natural shelter from prevailing S and SW swell. Warm Agulhas water. Hobie Beach hosts major OW events. In strong SW wind the bay can be choppy despite low swell. Exposed to NE wind and NE swell which arrive less frequently. An established OW swim community uses this stretch regularly.',
  },
  {
    id: 'east-london-eastern-beach',
    name: 'Eastern Beach, East London',
    region: 'Eastern Cape',
    aliases: ['east london', 'eastern beach', 'eastern beach east london', 'orient beach', 'orient beach east london', 'nahoon beach'],
    lat: -33.0167, lon: 27.9167,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Eastern Beach and Orient Beach are the main guarded swim venues in East London. Warm Indian Ocean. Exposed to S and SW swell. Shore break can be significant on bigger swell days. After heavy rain the Buffalo River outflow affects water quality near the river mouth. Lifeguards patrol in season — check flag status.',
  },
  {
    id: 'kenton-river',
    name: 'Kenton-on-Sea (Bushmans River)',
    region: 'Eastern Cape',
    aliases: ['kenton', 'kenton on sea', 'kenton-on-sea', 'bushmans river', 'kariega river'],
    lat: -33.6833, lon: 26.6667,
    hasMarine: false, isTidal: true, tidalType: 'permanent',
    exposure: 'sheltered',
    profile: 'The Bushmans and Kariega rivers provide sheltered tidal estuary swimming — this is where OW swimming in the Kenton area happens, not the open coast. Warm water. Calm flat water away from the main tidal flow. Tidal current runs through the channels — check state before swimming near the mouth. River water quality can be affected after heavy rain upstream.',
  },
  {
    id: 'port-alfred',
    name: 'Port Alfred',
    region: 'Eastern Cape',
    aliases: ['port alfred', 'kowie', 'kowie beach', 'port alfred beach', "kelly's beach", 'east beach port alfred'],
    lat: -33.5950, lon: 26.8950,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Kelly\'s Beach and East Beach are the main swim spots. Warm Agulhas water. Exposed to S and SW swell. Kowie River mouth creates rip risk when flowing strongly — avoid the immediate mouth area after rain. East Beach is marginally more sheltered from the prevailing swell direction. Lifeguards in season.',
  },
  {
    id: 'chintsa',
    name: 'Chintsa',
    region: 'Eastern Cape',
    aliases: ['chintsa', 'chintsa beach', 'chintsa east', 'chintsa west'],
    lat: -32.7833, lon: 28.1333,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Holiday beach between East London and Morgan Bay. Exposed to S and SW swell. Warm Indian Ocean. River mouth nearby — avoid after heavy rain. Quiet and uncrowded with no permanent lifeguard service — self-rescue conditions apply.',
  },
  {
    id: 'morgan-bay',
    name: 'Morgan Bay',
    region: 'Eastern Cape',
    aliases: ['morgan bay', "morgan's bay", 'morgans bay'],
    lat: -32.6833, lon: 28.3667,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Small holiday village. The beach inside the river mouth offers calmer conditions than the open ocean side. Warm Indian Ocean. Exposed to S and SW swell on the ocean beach. No permanent lifeguard service — self-rescue conditions. Quieter and more remote than East London beaches.',
  },

  // ── SOUTH COAST ───────────────────────────────────────────────────────────
  {
    id: 'hermanus',
    name: 'Hermanus',
    region: 'South Coast',
    aliases: ['hermanus', 'grotto beach', 'walker bay'],
    lat: -34.4178, lon: 19.2353,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Walker Bay — sheltered from prevailing SW swell. Exposed to SE and E swell.',
  },

  // ── FALSE BAY ─────────────────────────────────────────────────────────────
  {
    id: 'gordons-bay',
    name: "Gordon's Bay",
    region: 'False Bay',
    aliases: ["gordons bay", "gordon's bay"],
    lat: -34.1667, lon: 18.8667,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered bay in False Bay. Protected from SW swell. False Bay water significantly warmer than Atlantic side in summer.',
  },
  {
    id: 'fish-hoek',
    name: 'Fish Hoek',
    region: 'False Bay',
    aliases: ['fish hoek', 'fishhoek'],
    lat: -34.1376, lon: 18.4311,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered False Bay beach. White shark presence — check SharkSpotter status before entering.',
  },
  {
    id: 'glencairn',
    name: 'Glencairn',
    region: 'False Bay',
    aliases: ['glencairn', 'glencairn beach'],
    lat: -34.1500, lon: 18.4333,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered False Bay beach between Fish Hoek and Simon\'s Town. Generally calm. White shark area — check SharkSpotter status.',
  },
  {
    id: 'boulders-beach',
    name: 'Boulders Beach',
    region: 'False Bay',
    aliases: ['boulders', 'boulders beach', 'simons town'],
    lat: -34.1981, lon: 18.4517,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered coves between granite boulders near Simon\'s Town. Protected from most swell. Penguin colony. Very calm water.',
  },
  {
    id: 'simons-town-long-beach',
    name: "Simons Town Long Beach",
    region: 'False Bay',
    aliases: ['simons town long beach', 'long beach simons town', 'simons town beach'],
    lat: -34.1897, lon: 18.4322,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered False Bay beach near Simons Town. Protected from SW swell. Calm clear water. White shark area — check SharkSpotter status.',
  },
  {
    id: 'millers-point',
    name: "Millers Point",
    region: 'False Bay',
    aliases: ['millers point', 'miller point'],
    lat: -34.2167, lon: 18.4500,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Rocky False Bay cove south of Simons Town. Sheltered from SW swell. Clear cold water. Popular shore dive and swim spot.',
  },
  {
    id: 'seaforth-beach',
    name: 'Seaforth Beach',
    region: 'False Bay',
    aliases: ['seaforth', 'seaforth beach'],
    lat: -34.1950, lon: 18.4380,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered False Bay beach adjacent to Boulders. Calm water. Penguin colony nearby. White shark area.',
  },

  // ── ATLANTIC SEABOARD ─────────────────────────────────────────────────────
  {
    id: 'clifton-4th',
    name: 'Clifton 4th Beach',
    region: 'Atlantic Seaboard',
    aliases: ['clifton', 'clifton 4th', 'clifton 4', 'clifton beach', 'clifton 4th beach'],
    lat: -33.9337, lon: 18.3733,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Sheltered from S swell by Lion\'s Head. Cold Benguela upwelling — water 12–16°C even in summer.',
  },
  {
    id: 'clifton-1st',
    name: 'Clifton 1st Beach',
    region: 'Atlantic Seaboard',
    aliases: ['clifton 1st', 'clifton 1', 'clifton first'],
    lat: -33.9290, lon: 18.3760,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Northernmost Clifton beach, slightly more exposed than 4th. Cold Benguela water. Generally calm in light conditions.',
  },
  {
    id: 'beta-beach',
    name: 'Beta Beach',
    region: 'Atlantic Seaboard',
    aliases: ['beta beach', 'beta'],
    lat: -33.9270, lon: 18.3780,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Small rocky cove near Clifton. Protected in light conditions. Cold Atlantic water.',
  },
  {
    id: 'bakoven',
    name: 'Bakoven',
    region: 'Atlantic Seaboard',
    aliases: ['bakoven', 'bakoven beach'],
    lat: -33.9430, lon: 18.3660,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Rocky cove just south of Camps Bay. Sheltered by boulders. Cold Benguela water. Popular with local swimmers.',
  },
  {
    id: 'camps-bay',
    name: 'Camps Bay',
    region: 'Atlantic Seaboard',
    aliases: ['camps bay', 'campsbay'],
    lat: -33.9489, lon: 18.3773,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Open beach with some S swell exposure. Cold Benguela water. SE wind (Cape Doctor) creates strong onshore chop in summer afternoons.',
  },
  {
    id: 'bantry-bay',
    name: 'Bantry Bay',
    region: 'Atlantic Seaboard',
    aliases: ['bantry bay', 'bantrybay'],
    lat: -33.9220, lon: 18.3810,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Rocky cove between Sea Point and Clifton. Sheltered from S swell. Cold Atlantic water. Rocky entry.',
  },
  {
    id: 'cosy-bay',
    name: 'Cosy Bay',
    region: 'Atlantic Seaboard',
    aliases: ['cosy bay', 'cosybay'],
    lat: -33.9200, lon: 18.3820,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Small rocky cove on the Atlantic Seaboard. Sheltered. Cold water. Local swimmers only.',
  },
  {
    id: 'sea-point',
    name: 'Sea Point',
    region: 'Atlantic Seaboard',
    aliases: ['sea point', 'seapoint', 'queens beach', 'milton pool'],
    lat: -33.9042, lon: 18.3791,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Fully exposed Atlantic seaboard. Cold Benguela — water 12–16°C year-round. Heavy swell possible. Tidal pool offers shelter when ocean is rough.',
  },
  {
    id: 'saunders-rock',
    name: 'Saunders Rock',
    region: 'Atlantic Seaboard',
    aliases: ['saunders', 'saunders rock', 'saunders beach'],
    lat: -33.9150, lon: 18.3800,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Rocky outcrop on the Atlantic Seaboard between Sea Point and Bantry Bay. Cold water. Some shelter from S swell.',
  },
  {
    id: 'hout-bay',
    name: 'Hout Bay',
    region: 'Atlantic Seaboard',
    aliases: ['hout bay', 'houtbay'],
    lat: -34.0469, lon: 18.3614,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Bay sheltered from S swell by the surrounding mountains. Exposed to NW wind and swell. Cold Benguela water. Seal island nearby.',
  },

  // ── WEST COAST ────────────────────────────────────────────────────────────
  {
    id: 'big-bay',
    name: 'Big Bay',
    region: 'West Coast',
    aliases: ['big bay', 'bigbay', 'blouberg big bay'],
    lat: -33.8000, lon: 18.4833,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Fully exposed to S and SW swell and SE wind. Strong Cape Doctor chop in summer. Cold Benguela water. Kitesurfing hub — watch for boards.',
  },
  {
    id: 'blouberg',
    name: 'Blouberg (Dolphin Beach)',
    region: 'West Coast',
    aliases: ['blouberg', 'dolphin beach', 'bloubergstrand'],
    lat: -33.8167, lon: 18.4667,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open Atlantic beach fully exposed to S and SW swell and SE wind. Cold water. Table Mountain views.',
  },
  {
    id: 'melkbosstrand',
    name: 'Melkbosstrand',
    region: 'West Coast',
    aliases: ['melkbosstrand', 'melkbos'],
    lat: -33.7167, lon: 18.4333,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open Atlantic beach north of Cape Town. Exposed to S and SW swell. Cold Benguela water. Long beach swim stretch.',
  },
  {
    id: 'milnerton',
    name: 'Milnerton',
    region: 'West Coast',
    aliases: ['milnerton', 'milnerton beach'],
    lat: -33.8667, lon: 18.4833,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open beach at the mouth of the Diep River. Exposed to S and SW swell. SE wind creates significant chop. Cold water.',
  },
  {
    id: 'derdesteen',
    name: 'Derdesteen',
    region: 'West Coast',
    aliases: ['derdesteen', 'derde steen'],
    lat: -33.7600, lon: 18.4400,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'West Coast beach north of Melkbosstrand. Exposed Atlantic beach. Cold Benguela water.',
  },
  {
    id: 'small-bay',
    name: 'Small Bay',
    region: 'West Coast',
    aliases: ['small bay', 'smallbay', 'langebaan small bay'],
    lat: -33.0833, lon: 18.0333,
    hasMarine: false, isTidal: true,
    exposure: 'sheltered',
    profile: 'Sheltered lagoon arm of Langebaan, West Coast National Park. Flat water, warm in summer. Popular triathlon venue.',
  },
  {
    id: 'st-helena-bay',
    name: 'St Helena Bay',
    region: 'West Coast',
    aliases: ['st helena bay', 'saint helena bay'],
    lat: -32.7500, lon: 18.0000,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Large bay on the West Coast. Semi-sheltered from S swell. Cold upwelling water. Remote — plan accordingly.',
  },
  {
    id: 'yzerfontein',
    name: 'Yzerfontein',
    region: 'West Coast',
    aliases: ['yzerfontein', 'yzerfontein beach'],
    lat: -33.3500, lon: 18.1667,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Remote West Coast beach. Fully exposed to S and SW swell. Cold Benguela water. Rocky reef entries.',
  },
  {
    id: 'silwerstroomstrand',
    name: 'Silwerstroomstrand',
    region: 'West Coast',
    aliases: ['silwerstroomstrand', 'silwerstroom'],
    lat: -33.5500, lon: 18.3000,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open West Coast beach. Exposed to S and SW swell. Cold water. Day visitor reserve.',
  },
  {
    id: 'robben-island',
    name: 'Robben Island',
    region: 'West Coast',
    aliases: ['robben island', 'robbeneiland'],
    lat: -33.8078, lon: 18.3667,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open Atlantic water around the island. Fully exposed. Cold Benguela current. Significant currents in the channel. Primarily a marathon swim destination.',
  },
  {
    id: 'paternoster',
    name: 'Paternoster',
    region: 'West Coast',
    aliases: ['paternoster', 'paternoster beach'],
    lat: -32.8167, lon: 17.8833,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Small bay on the West Coast. Some shelter from prevailing SW swell. Cold Benguela water. Remote — plan accordingly.',
  },
  {
    id: 'langebaan',
    name: 'Langebaan Lagoon',
    region: 'West Coast',
    aliases: ['langebaan', 'langebaan lagoon', 'club mykonos'],
    lat: -33.1000, lon: 18.0333,
    hasMarine: false, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered West Coast lagoon in the West Coast National Park. Flat calm water. Warm in summer. No sharks. Popular triathlon and open water venue.',
  },

  // ── KWAZULU-NATAL ─────────────────────────────────────────────────────────
  {
    id: 'umdloti',
    name: 'Umdloti',
    region: 'KwaZulu-Natal',
    aliases: ['umdloti', 'umdloti beach'],
    lat: -29.6167, lon: 31.1333,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'KZN north coast beach. Warm Indian Ocean water. Some protection from the reef. Watch for rip currents. KZN Sharks Board protection at main beach — check current status.',
  },
  {
    id: 'umhlanga',
    name: 'Umhlanga',
    region: 'KwaZulu-Natal',
    aliases: ['umhlanga', 'umhlanga beach', 'umhlanga rocks'],
    lat: -29.7247, lon: 31.0792,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Popular KZN beach north of Durban. Warm Indian Ocean. KZN Sharks Board protection in season. Check flag status before swimming.',
  },
  {
    id: 'durban-beach-club',
    name: 'Durban Undersea Club',
    region: 'KwaZulu-Natal',
    aliases: ['durban beach club', 'duc', 'durban underwater club', 'durban undersea club', 'vetch\'s beach', 'point durban'],
    lat: -29.8728, lon: 31.0438,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Point Promenade, southern end of the Durban beachfront at the harbour entrance. Beach protected by the Vetch\'s Pier breakwater — calmer than open beachfront. Warm Indian Ocean. KZN Sharks Board protection. The main open water swim venue for Durban-based swimmers.',
  },
  {
    id: 'north-beach-durban',
    name: 'North Beach Durban',
    region: 'KwaZulu-Natal',
    aliases: ['north beach', 'north beach durban', 'ushaka beach', 'addington beach'],
    lat: -29.8500, lon: 31.0500,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Main Durban beachfront stretch running north from uShaka. Warm Indian Ocean. KZN Sharks Board protection. Busy beach with lifeguards. Approximately 2.5km north of the Underwater Club.',
  },
  {
    id: 'ballito',
    name: 'Ballito',
    region: 'KwaZulu-Natal',
    aliases: ['ballito', 'ballito beach'],
    lat: -29.5333, lon: 31.2167,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'North coast KZN beach. Warm Indian Ocean. Reef offers some protection. KZN Sharks Board protection at main beach — check status.',
  },
  {
    id: 'salt-rock',
    name: 'Salt Rock',
    region: 'KwaZulu-Natal',
    aliases: ['salt rock', 'saltrock'],
    lat: -29.4833, lon: 31.2333,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Tidal pool and beach on the KZN north coast. Rock ledge offers some protection. Warm water.',
  },
  {
    id: 'thompsons-bay',
    name: "Thompson's Bay",
    region: 'KwaZulu-Natal',
    aliases: ["thompsons bay", "thompson's bay", "thompsonsbay"],
    lat: -29.4667, lon: 31.2500,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Small sheltered bay on the KZN north coast. Rock ledge provides some protection from swell. Warm water.',
  },
  {
    id: 'umhloti',
    name: 'Umhloti',
    region: 'KwaZulu-Natal',
    aliases: ['umhloti', 'umhloti beach'],
    lat: -29.6333, lon: 31.1167,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'KZN north coast beach near Umdloti. Warm Indian Ocean. River mouth nearby — avoid after heavy rain.',
  },
  {
    id: 'amanzimtoti',
    name: 'Amanzimtoti',
    region: 'KwaZulu-Natal',
    aliases: ['amanzimtoti', 'toti', 'inyoni rocks'],
    lat: -30.0500, lon: 30.8833,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'KZN south coast beach. Warm Indian Ocean. KZN Sharks Board protection at main beaches. Check flag status before entering.',
  },
  {
    id: scottsburgh', 
    name: 'Scottburgh',
    region: 'KwaZulu-Natal',
    aliases: ['scottburgh', 'scottburgh beach''scottsburgh', 'scottsburgh beach'],
    lat: -30.2833, lon: 30.7667,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'KZN south coast town beach. Warm Indian Ocean. KZN Sharks Board protection at main beach — check seasonal status. Exposed to S and SW swell. Tidal pool offers a calmer alternative when ocean is rough. Popular holiday swim destination with lifeguards in season.',
  },
  {
    id: 'hibberdene',
    name: 'Hibberdene',
    region: 'KwaZulu-Natal',
    aliases: ['hibberdene', 'hibberdene beach'],
    lat: -30.5667, lon: 30.5833,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Mid-south coast KZN holiday beach. Warm Indian Ocean. Exposed to S and SW swell. KZN Sharks Board protection at the main beach — check current status before entering. River mouth nearby — avoid after heavy rain.',
  },
  {
    id: 'margate',
    name: 'Margate',
    region: 'KwaZulu-Natal',
    aliases: ['margate', 'margate beach', 'south beach margate', 'ramsgate', 'uvongo'],
    lat: -30.8500, lon: 30.3667,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Hub of the KZN lower south coast. Warm Indian Ocean. KZN Sharks Board protection at main beach — check seasonal status. Exposed to S and SW swell; shore break can be heavy after E swell. Lifeguards in season. Uvongo and Ramsgate a few km north offer similar conditions.',
  },
  {
    id: 'shakas-rock',
    name: "Shaka's Rock",
    region: 'KwaZulu-Natal',
    aliases: ["shaka's rock", 'shakas rock', 'shakasrock', 'tinley manor'],
    lat: -29.4167, lon: 31.2667,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Rocky headland on the KZN north coast. Tidal pool offers sheltered calm-water swimming and is the preferred OW swim venue here. Ocean side exposed to E and NE swell. Warm Indian Ocean. Reef entry on the ocean side requires care at low tide.',
  },
  {
    id: 'blythedale',
    name: 'Blythedale Beach',
    region: 'KwaZulu-Natal',
    aliases: ['blythedale', 'blythedale beach'],
    lat: -29.2833, lon: 31.3167,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Long sandy beach north of the main tourist strip on the KZN north coast. Warm Indian Ocean. Exposed to NE and E swell. Quieter and less developed than the Ballito cluster. Avoid swimming near river mouths after heavy rain.',
  },
  {
    id: 'richards-bay',
    name: 'Richards Bay',
    region: 'KwaZulu-Natal',
    aliases: ['richards bay', 'richardsbay', 'meerensee'],
    lat: -28.7833, lon: 32.0667,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Meerensee beach is the main swim spot in Richards Bay. The bay offers partial shelter from ocean swell. Warm Indian Ocean. KZN Sharks Board protection at the main beach — verify current status. Harbour activity in the wider bay — stay within designated swim areas.',
  },
  {
    id: 'sodwana-bay',
    name: 'Sodwana Bay',
    region: 'KwaZulu-Natal',
    aliases: ['sodwana', 'sodwana bay'],
    lat: -27.5333, lon: 32.6833,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Remote northern KZN bay within iSimangaliso Wetland Park. Warm, clear Indian Ocean with excellent visibility. Coral reef offshore gives partial protection from ocean swell. Primarily a dive destination — significant boat traffic in the launch area. Swimmers should stay well clear of the boat channel and use a tow float. Access via gravel road through the park.',
  },

  // ── NAMIBIA ───────────────────────────────────────────────────────────────
  {
    id: 'swakopmund',
    name: 'Swakopmund Beach',
    region: 'Namibia',
    aliases: ['swakopmund', 'swakopmund beach'],
    lat: -22.6784, lon: 14.5254,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Cold Benguela current — water often 14–18°C. Exposed Atlantic beach. Strong currents. Fog common. Wetsuit essential.',
  },
  {
    id: 'walvis-bay',
    name: 'Walvis Bay',
    region: 'Namibia',
    aliases: ['walvis bay', 'walvisbay'],
    lat: -22.9575, lon: 14.5053,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Sheltered lagoon bay. Cold Benguela water. Flamingo habitat. Calmer than open Swakopmund beach.',
  },

];

export function matchSpot(query) {
  const q = query.toLowerCase().trim();
  return SPOTS.find(s => s.aliases.some(a => q.includes(a) || a.includes(q)));
}

// Quick chips on the idle screen — one per region
export const QUICK_SPOT_IDS = [
  'knysna-heads', 'knysna-lagoon', 'buffalo-bay',
  'clifton-4th', 'camps-bay', 'umhlanga',
];

export function quickSpots() {
  return SPOTS.filter(s => QUICK_SPOT_IDS.includes(s.id));
}

export function spotsByRegion() {
  const regions = {};
  SPOTS.forEach(s => {
    if (!regions[s.region]) regions[s.region] = [];
    regions[s.region].push(s);
  });
  return regions;
}
