export const SPOTS = [
  {
    id: 'knysna-heads',
    name: 'Knysna Heads',
    aliases: ['knysna heads', 'the heads'],
    lat: -34.0797,
    lon: 23.0530,
    hasMarine: true,
    isTidal: true,
    tidalType: 'semidiurnal',
    exposure: 'open ocean',
    profile: 'Open ocean entry through a narrow tidal channel. Significant S and SW swell penetrates. Strong tidal currents — direction and timing critical. Not suitable above 1.5m swell.',
    tidalNote: 'Channel current runs strong on spring tides. Outgoing tide pulls toward the ocean; incoming pushes into the lagoon. Slack water near the turns offers the calmest entry.',
  },
  {
    id: 'knysna-lagoon',
    name: 'Knysna Lagoon',
    aliases: ['knysna lagoon', 'knysna estuary', 'thesen island', 'yacht club', 'knysna yacht club'],
    lat: -34.0556,
    lon: 23.0497,
    hasMarine: false,
    isTidal: true,
    tidalType: 'semidiurnal',
    exposure: 'sheltered',
    profile: 'Sheltered tidal estuary. No ocean swell penetrates. Conditions driven by local wind — easterly and westerly breezes create surface chop. Water typically warmer than the sea.',
    tidalNote: 'Tidal current runs throughout most of the cycle — strongest mid-tide, slack near the turns. Spring tides produce a noticeably stronger pull toward the Heads on the outgoing.',
  },
  {
    id: 'buffalo-bay',
    name: 'Buffalo Bay',
    aliases: ['buffalo bay', 'buffels bay', 'buffelsbay'],
    lat: -34.1082,
    lon: 22.9897,
    hasMarine: true,
    isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Semi-sheltered bay facing SSW. Some S-SW swell penetration but generally calmer than the Heads. Shore break on the sand beach.',
    tidalNote: null,
  },
  {
    id: 'wilderness',
    name: 'Wilderness Beach',
    aliases: ['wilderness', 'wilderness beach'],
    lat: -33.9897,
    lon: 22.5933,
    hasMarine: true,
    isTidal: false,
    exposure: 'open ocean',
    profile: 'Open-ocean beach fully exposed to S and SW swell. Shore break can be heavy. Rip currents possible in larger swell.',
    tidalNote: null,
  },
  {
    id: 'plett-main',
    name: 'Plett Main Beach',
    aliases: ['plett', 'plettenberg bay', 'plett main', 'main beach plett'],
    lat: -34.0520,
    lon: 23.3707,
    hasMarine: true,
    isTidal: false,
    exposure: 'open ocean',
    profile: 'Open ocean beach exposed to S and SW swell. Swell wraps around the headlands. Check for rips near the river mouth.',
    tidalNote: null,
  },
  {
    id: 'robberg',
    name: 'Robberg Beach',
    aliases: ['robberg', 'robberg beach'],
    lat: -34.0750,
    lon: 23.3800,
    hasMarine: true,
    isTidal: false,
    exposure: 'open ocean',
    profile: 'Exposed open beach on eastern side of Robberg Peninsula. Full S and SW swell exposure. Strong currents off the point.',
    tidalNote: null,
  },
  {
    id: 'clifton-4th',
    name: 'Clifton 4th Beach',
    aliases: ['clifton', 'clifton 4th', 'clifton 4', 'clifton beach'],
    lat: -33.9337,
    lon: 18.3733,
    hasMarine: true,
    isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Sheltered from S swell by Lion\'s Head. Cold Benguela upwelling — water 12–16°C even in summer. Generally calm surface.',
    tidalNote: null,
  },
  {
    id: 'camps-bay',
    name: 'Camps Bay',
    aliases: ['camps bay', 'campsbay'],
    lat: -33.9489,
    lon: 18.3773,
    hasMarine: true,
    isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Open beach with some S swell exposure. Cold Benguela water. SE wind (Cape Doctor) creates strong onshore chop in summer afternoons.',
    tidalNote: null,
  },
  {
    id: 'sea-point',
    name: 'Sea Point',
    aliases: ['sea point', 'seapoint'],
    lat: -33.9042,
    lon: 18.3791,
    hasMarine: true,
    isTidal: false,
    exposure: 'open ocean',
    profile: 'Fully exposed Atlantic seaboard. Cold Benguela — water 12–16°C year-round. Heavy swell possible. Tidal pool offers shelter when ocean is rough.',
    tidalNote: null,
  },
  {
    id: 'hermanus',
    name: 'Hermanus',
    aliases: ['hermanus', 'grotto beach'],
    lat: -34.4178,
    lon: 19.2353,
    hasMarine: true,
    isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Walker Bay — sheltered from prevailing SW swell. Exposed to SE and E swell.',
    tidalNote: null,
  },
  {
    id: 'gordons-bay',
    name: "Gordon's Bay",
    aliases: ["gordons bay", "gordon's bay"],
    lat: -34.1667,
    lon: 18.8667,
    hasMarine: true,
    isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered bay in False Bay. Protected from SW swell. False Bay water significantly warmer than Atlantic side in summer.',
    tidalNote: null,
  },
  {
    id: 'fish-hoek',
    name: 'Fish Hoek',
    aliases: ['fish hoek', 'fishhoek'],
    lat: -34.1376,
    lon: 18.4311,
    hasMarine: true,
    isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered False Bay beach. White shark presence — check SharkSpotter status before entering.',
    tidalNote: null,
  },
];

export function matchSpot(query) {
  const q = query.toLowerCase().trim();
  return SPOTS.find(s => s.aliases.some(a => q.includes(a) || a.includes(q)));
}

export const QUICK_SPOTS = ['knysna-heads', 'knysna-lagoon', 'buffalo-bay', 'wilderness', 'clifton-4th', 'camps-bay'];
export const quickSpots = () => SPOTS.filter(s => QUICK_SPOTS.includes(s.id));
