export const SPOTS = [

  // ── GARDEN ROUTE ──────────────────────────────────────────────────────────
  {
    id: 'knysna-heads',
    name: 'Knysna Heads',
    region: 'Garden Route',
    aliases: ['knysna heads', 'the heads'],
    lat: -34.0797, lon: 23.0530,
    hasMarine: true, isTidal: true,
    exposure: 'open ocean',
    profile: 'Open ocean entry through a narrow tidal channel. Significant S and SW swell penetrates. Strong tidal currents — direction and timing critical. Not suitable above 1.5m swell.',
  },
  {
    id: 'knysna-lagoon',
    name: 'Knysna Lagoon',
    region: 'Garden Route',
    aliases: ['knysna lagoon', 'knysna estuary', 'thesen island', 'yacht club', 'knysna yacht club'],
    lat: -34.0556, lon: 23.0497,
    hasMarine: false, isTidal: true,
    exposure: 'sheltered',
    profile: 'Sheltered tidal estuary. No ocean swell. Conditions driven by local wind. Water typically warmer than the sea.',
  },
  {
    id: 'buffalo-bay',
    name: 'Buffalo Bay',
    region: 'Garden Route',
    aliases: ['buffalo bay', 'buffels bay', 'buffelsbay'],
    lat: -34.1082, lon: 22.9897,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Semi-sheltered bay facing SSW. Some S-SW swell penetration but generally calmer than the Heads. Shore break on the sand beach.',
  },
  {
    id: 'wilderness-beach',
    name: 'Wilderness Beach',
    region: 'Garden Route',
    aliases: ['wilderness', 'wilderness beach'],
    lat: -33.9897, lon: 22.5933,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open-ocean beach fully exposed to S and SW swell. Shore break can be heavy. Rip currents possible.',
  },
  {
    id: 'sedgefield-lagoon',
    name: 'Sedgefield Lagoon',
    region: 'Garden Route',
    aliases: ['sedgefield', 'sedgefield lagoon', 'swartvlei'],
    lat: -34.0167, lon: 22.7833,
    hasMarine: false, isTidal: true,
    exposure: 'sheltered',
    profile: 'Sheltered coastal lagoon (Swartvlei). No ocean swell. Wind-driven surface conditions. Tidal exchange at the mouth.',
  },
  {
    id: 'mossel-bay',
    name: 'Mossel Bay',
    region: 'Garden Route',
    aliases: ['mossel bay', 'mosselbay'],
    lat: -34.1833, lon: 22.1500,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Protected bay offering shelter from prevailing SW swell. Exposed to SE and E swell. Santos Beach is the main swim spot.',
  },
  {
    id: 'santos-beach',
    name: 'Santos Beach',
    region: 'Garden Route',
    aliases: ['santos', 'santos beach'],
    lat: -34.1757, lon: 22.1396,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Sheltered beach within Mossel Bay, protected from SW swell. One of the calmer Garden Route ocean swims.',
  },
  {
    id: 'plett-main',
    name: 'Plett Main Beach',
    region: 'Garden Route',
    aliases: ['plett', 'plettenberg bay', 'plett main', 'main beach plett'],
    lat: -34.0520, lon: 23.3707,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open ocean beach exposed to S and SW swell. Swell wraps around the headlands. Check for rips near the river mouth.',
  },
  {
    id: 'robberg-beach',
    name: 'Robberg Beach',
    region: 'Garden Route',
    aliases: ['robberg', 'robberg beach'],
    lat: -34.0750, lon: 23.3800,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Exposed open beach on eastern side of Robberg Peninsula. Full S and SW swell exposure. Strong currents off the point.',
  },

  // ── EASTERN CAPE ──────────────────────────────────────────────────────────
  {
    id: 'jeffreys-bay',
    name: "Jeffreys Bay",
    region: 'Eastern Cape',
    aliases: ["jeffreys bay", "j-bay", "jbay"],
    lat: -34.0500, lon: 24.9333,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'World-class surf break, fully exposed to S and SW swell. Strong longshore currents. The point creates significant wave energy.',
  },
  {
    id: 'st-francis-bay',
    name: 'St Francis Bay',
    region: 'Eastern Cape',
    aliases: ['st francis bay', 'st francis', 'saint francis'],
    lat: -34.1833, lon: 24.8333,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Sheltered bay offering some protection from prevailing SW swell. Cape St Francis point creates varying conditions.',
  },
  {
    id: 'kenton-on-sea',
    name: 'Kenton-on-Sea',
    region: 'Eastern Cape',
    aliases: ['kenton', 'kenton on sea', 'kenton-on-sea'],
    lat: -33.6833, lon: 26.6667,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open coast between the Bushmans and Kariega river mouths. Exposed to S swell. River mouth rips possible after rain.',
  },

  // ── SOUTH COAST ───────────────────────────────────────────────────────────
  {
    id: 'hermanus',
    name: 'Hermanus',
    region: 'South Coast',
    aliases: ['hermanus', 'grotto beach', 'walker bay'],
    lat: -34.4178, lon: 19.2353,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Walker Bay — sheltered from prevailing SW swell. Exposed to SE and E swell.',
  },

  // ── FALSE BAY ─────────────────────────────────────────────────────────────
  {
    id: 'gordons-bay',
    name: "Gordon's Bay",
    region: 'False Bay',
    aliases: ["gordons bay", "gordon's bay"],
    lat: -34.1667, lon: 18.8667,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered bay in False Bay. Protected from SW swell. False Bay water significantly warmer than Atlantic side in summer.',
  },
  {
    id: 'fish-hoek',
    name: 'Fish Hoek',
    region: 'False Bay',
    aliases: ['fish hoek', 'fishhoek'],
    lat: -34.1376, lon: 18.4311,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered False Bay beach. White shark presence — check SharkSpotter status before entering.',
  },
  {
    id: 'glencairn',
    name: 'Glencairn',
    region: 'False Bay',
    aliases: ['glencairn', 'glencairn beach'],
    lat: -34.1500, lon: 18.4333,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered False Bay beach between Fish Hoek and Simon\'s Town. Generally calm. White shark area.',
  },
  {
    id: 'boulders-beach',
    name: 'Boulders Beach',
    region: 'False Bay',
    aliases: ['boulders', 'boulders beach', 'simons town'],
    lat: -34.1981, lon: 18.4517,
    hasMarine: true, isTidal: false,
    exposure: 'sheltered',
    profile: 'Sheltered coves between granite boulders near Simon\'s Town. Protected from most swell. Penguin colony. Very calm water.',
  },

  // ── ATLANTIC SEABOARD ─────────────────────────────────────────────────────
  {
    id: 'clifton-4th',
    name: 'Clifton 4th Beach',
    region: 'Atlantic Seaboard',
    aliases: ['clifton', 'clifton 4th', 'clifton 4', 'clifton beach', 'clifton 4th beach'],
    lat: -33.9337, lon: 18.3733,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Sheltered from S swell by Lion\'s Head. Cold Benguela upwelling — water 12–16°C even in summer.',
  },
  {
    id: 'clifton-1st',
    name: 'Clifton 1st Beach',
    region: 'Atlantic Seaboard',
    aliases: ['clifton 1st', 'clifton 1', 'clifton first'],
    lat: -33.9290, lon: 18.3760,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Northernmost Clifton beach, slightly more exposed than 4th. Cold Benguela water. Generally calm in light conditions.',
  },
  {
    id: 'beta-beach',
    name: 'Beta Beach',
    region: 'Atlantic Seaboard',
    aliases: ['beta beach', 'beta'],
    lat: -33.9270, lon: 18.3780,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Small rocky cove near Clifton. Protected in light conditions. Cold Atlantic water.',
  },
  {
    id: 'bakoven',
    name: 'Bakoven',
    region: 'Atlantic Seaboard',
    aliases: ['bakoven', 'bakoven beach'],
    lat: -33.9430, lon: 18.3660,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Rocky cove just south of Camps Bay. Sheltered by boulders. Cold Benguela water. Popular with local swimmers.',
  },
  {
    id: 'camps-bay',
    name: 'Camps Bay',
    region: 'Atlantic Seaboard',
    aliases: ['camps bay', 'campsbay'],
    lat: -33.9489, lon: 18.3773,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Open beach with some S swell exposure. Cold Benguela water. SE wind (Cape Doctor) creates strong onshore chop in summer afternoons.',
  },
  {
    id: 'bantry-bay',
    name: 'Bantry Bay',
    region: 'Atlantic Seaboard',
    aliases: ['bantry bay', 'bantrybay'],
    lat: -33.9220, lon: 18.3810,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Rocky cove between Sea Point and Clifton. Sheltered from S swell. Cold Atlantic water. Rocky entry.',
  },
  {
    id: 'cosy-bay',
    name: 'Cosy Bay',
    region: 'Atlantic Seaboard',
    aliases: ['cosy bay', 'cosybay'],
    lat: -33.9200, lon: 18.3820,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Small rocky cove on the Atlantic Seaboard. Sheltered. Cold water. Local swimmers only.',
  },
  {
    id: 'sea-point',
    name: 'Sea Point',
    region: 'Atlantic Seaboard',
    aliases: ['sea point', 'seapoint', 'queens beach', 'milton pool'],
    lat: -33.9042, lon: 18.3791,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Fully exposed Atlantic seaboard. Cold Benguela — water 12–16°C year-round. Heavy swell possible. Tidal pool offers shelter when ocean is rough.',
  },
  {
    id: 'saunders-rock',
    name: 'Saunders Rock',
    region: 'Atlantic Seaboard',
    aliases: ['saunders', 'saunders rock', 'saunders beach'],
    lat: -33.9150, lon: 18.3800,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Rocky outcrop on the Atlantic Seaboard between Sea Point and Bantry Bay. Cold water. Some shelter from S swell.',
  },
  {
    id: 'hout-bay',
    name: 'Hout Bay',
    region: 'Atlantic Seaboard',
    aliases: ['hout bay', 'houtbay'],
    lat: -34.0469, lon: 18.3614,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Bay sheltered from S swell by the surrounding mountains. Exposed to NW wind and swell. Cold Benguela water. Seal island nearby.',
  },
  {
    id: 'llandudno',
    name: 'Llandudno',
    region: 'Atlantic Seaboard',
    aliases: ['llandudno', 'llandudno beach'],
    lat: -34.0100, lon: 18.3450,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Exposed beach between Hout Bay and Camps Bay. Full S and SW swell exposure. Strong shore break. Cold water.',
  },

  // ── WEST COAST ────────────────────────────────────────────────────────────
  {
    id: 'big-bay',
    name: 'Big Bay',
    region: 'West Coast',
    aliases: ['big bay', 'bigbay'],
    lat: -33.8000, lon: 18.4833,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Fully exposed to S and SW swell and SE wind. Strong Cape Doctor chop in summer. Cold Benguela water. Kitesurfing hub — watch for boards.',
  },
  {
    id: 'blouberg',
    name: 'Blouberg (Dolphin Beach)',
    region: 'West Coast',
    aliases: ['blouberg', 'dolphin beach', 'bloubergstrand'],
    lat: -33.8167, lon: 18.4667,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open Atlantic beach fully exposed to S and SW swell and SE wind. Cold water. Table Mountain views.',
  },
  {
    id: 'melkbosstrand',
    name: 'Melkbosstrand',
    region: 'West Coast',
    aliases: ['melkbosstrand', 'melkbos'],
    lat: -33.7167, lon: 18.4333,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open Atlantic beach north of Cape Town. Exposed to S and SW swell. Cold Benguela water. Long beach swim stretch.',
  },
  {
    id: 'milnerton',
    name: 'Milnerton',
    region: 'West Coast',
    aliases: ['milnerton', 'milnerton beach'],
    lat: -33.8667, lon: 18.4833,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open beach at the mouth of the Diep River. Exposed to S and SW swell. SE wind creates significant chop. Cold water.',
  },
  {
    id: 'derdesteen',
    name: 'Derdesteen',
    region: 'West Coast',
    aliases: ['derdesteen', 'derde steen'],
    lat: -33.7600, lon: 18.4400,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'West Coast beach north of Melkbosstrand. Exposed Atlantic beach. Cold Benguela water.',
  },
  {
    id: 'small-bay',
    name: 'Small Bay',
    region: 'West Coast',
    aliases: ['small bay', 'smallbay', 'langebaan small bay'],
    lat: -33.0833, lon: 18.0333,
    hasMarine: false, isTidal: true,
    exposure: 'sheltered',
    profile: 'Sheltered lagoon arm of Langebaan, West Coast National Park. Flat water, warm in summer. Popular triathlon venue.',
  },
  {
    id: 'st-helena-bay',
    name: 'St Helena Bay',
    region: 'West Coast',
    aliases: ['st helena bay', 'saint helena bay'],
    lat: -32.7500, lon: 18.0000,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Large bay on the West Coast. Semi-sheltered from S swell. Cold upwelling water. Remote — plan accordingly.',
  },
  {
    id: 'yzerfontein',
    name: 'Yzerfontein',
    region: 'West Coast',
    aliases: ['yzerfontein', 'yzerfontein beach'],
    lat: -33.3500, lon: 18.1667,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Remote West Coast beach. Fully exposed to S and SW swell. Cold Benguela water. Rocky reef entries.',
  },
  {
    id: 'silwerstroomstrand',
    name: 'Silwerstroomstrand',
    region: 'West Coast',
    aliases: ['silwerstroomstrand', 'silwerstroom'],
    lat: -33.5500, lon: 18.3000,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open West Coast beach. Exposed to S and SW swell. Cold water. Day visitor reserve.',
  },
  {
    id: 'robben-island',
    name: 'Robben Island',
    region: 'West Coast',
    aliases: ['robben island', 'robbeneiland'],
    lat: -33.8078, lon: 18.3667,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Open Atlantic water around the island. Fully exposed. Cold Benguela current. Significant currents in the channel. Primarily a marathon swim destination.',
  },

  // ── KWAZULU-NATAL ─────────────────────────────────────────────────────────
  {
    id: 'umdloti',
    name: 'Umdloti',
    region: 'KwaZulu-Natal',
    aliases: ['umdloti', 'umdloti beach'],
    lat: -29.6167, lon: 31.1333,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'KZN north coast beach. Warm Indian Ocean water. Some protection from the reef. Watch for rip currents. No shark nets at all beaches — check signage.',
  },
  {
    id: 'umhlanga',
    name: 'Umhlanga',
    region: 'KwaZulu-Natal',
    aliases: ['umhlanga', 'umhlanga beach', 'umhlanga rocks'],
    lat: -29.7247, lon: 31.0792,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Popular KZN beach north of Durban. Warm Indian Ocean. Shark nets in season. Check flag status before swimming.',
  },
  {
    id: 'durban-beach-club',
    name: 'Durban Beach Club',
    region: 'KwaZulu-Natal',
    aliases: ['durban beach club', 'duc', 'durban beach'],
    lat: -29.8654, lon: 31.0514,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Central Durban beachfront. Warm Indian Ocean. Shark nets. The main open water swim venue for Durban-based swimmers.',
  },
  {
    id: 'ballito',
    name: 'Ballito',
    region: 'KwaZulu-Natal',
    aliases: ['ballito', 'ballito beach'],
    lat: -29.5333, lon: 31.2167,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'North coast KZN beach. Warm Indian Ocean. Reef offers some protection. Check shark net status.',
  },
  {
    id: 'salt-rock',
    name: 'Salt Rock',
    region: 'KwaZulu-Natal',
    aliases: ['salt rock', 'saltrock'],
    lat: -29.4833, lon: 31.2333,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Tidal pool and beach on the KZN north coast. Rock ledge offers some protection. Warm water.',
  },
  {
    id: 'thompsons-bay',
    name: "Thompson's Bay",
    region: 'KwaZulu-Natal',
    aliases: ["thompsons bay", "thompson's bay", "thompsonsbay"],
    lat: -29.4667, lon: 31.2500,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Small sheltered bay on the KZN north coast. Rock ledge provides some protection from swell. Warm water.',
  },
  {
    id: 'umhloti',
    name: 'Umhloti',
    region: 'KwaZulu-Natal',
    aliases: ['umhloti', 'umhloti beach'],
    lat: -29.6333, lon: 31.1167,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'KZN north coast beach near Umdloti. Warm Indian Ocean. River mouth nearby — avoid after heavy rain.',
  },

  // ── NAMIBIA ───────────────────────────────────────────────────────────────
  {
    id: 'swakopmund',
    name: 'Swakopmund Beach',
    region: 'Namibia',
    aliases: ['swakopmund', 'swakopmund beach'],
    lat: -22.6784, lon: 14.5254,
    hasMarine: true, isTidal: false,
    exposure: 'open ocean',
    profile: 'Cold Benguela current — water often 14–18°C. Exposed Atlantic beach. Strong currents. Fog common. Wetsuit essential.',
  },
  {
    id: 'walvis-bay',
    name: 'Walvis Bay',
    region: 'Namibia',
    aliases: ['walvis bay', 'walvisbay'],
    lat: -22.9575, lon: 14.5053,
    hasMarine: true, isTidal: false,
    exposure: 'semi-sheltered',
    profile: 'Sheltered lagoon bay. Cold Benguela water. Flamingo habitat. Calmer than open Swakopmund beach.',
  },
];

export function matchSpot(query) {
  const q = query.toLowerCase().trim();
  return SPOTS.find(s => s.aliases.some(a => q.includes(a) || a.includes(q)));
}

// Quick chips on the idle screen — one per region
export const QUICK_SPOT_IDS = [
  'knysna-heads', 'knysna-lagoon', 'buffalo-bay',
  'clifton-4th', 'camps-bay', 'umhlanga',
];

export function quickSpots() {
  return SPOTS.filter(s => QUICK_SPOT_IDS.includes(s.id));
}

export function spotsByRegion() {
  const regions = {};
  SPOTS.forEach(s => {
    if (!regions[s.region]) regions[s.region] = [];
    regions[s.region].push(s);
  });
  return regions;
}
